### ISSUE TITLE
Privately using YCSB-C.

### ISSUE THREAD

**Issue by alokasok** [basicthinker/YCSB-C#1]
Hi,
I am planing to integrate the YCSB-C with my project for doing some testing. Is it ok to use as I didnt see a Open source license for the code.

Regards,

Alok Asok

**Comment by basicthinker** [comment]
Hi Alok,

Sure, feel free to use it. Let me know if any problem.

It would be better if you could fork and pull so that your contributions can be shared.

Please use the master branch. But you can refer to this quick start: https://github.com/basicthinker/YCSB-C/blob/undo/README.md, where you just ignore Step 2 and 3.2 which are for integration with my other projects.

I may compose a README for the master branch this week.

Thanks,
Jinglei

**Comment by alokasok** [comment]
Thanks a lot. I am still confused about where to get the sitevm dependency.
